[package]
name = "noodles-vcf"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
indexmap = "1.4.0"
nom = "6.1.2"
noodles-bgzf = { path = "../noodles-bgzf" }
noodles-core = { path = "../noodles-core" }
noodles-tabix = { path = "../noodles-tabix" }
percent-encoding = "2.1.0"
